#!/bin/bash
uname=`cat ~/.gitconfig | grep name | awk '{print $3}'`
echo " Your GIT username is $uname."
repo_name=`pwd | xargs basename`
echo " The name of the current directory will be the name of the repository."
echo " The repository name is setting up for $repo_name."
read -p " Please write in the first commit: " commit
#
echo " Create an empty Git repository."
git init
echo " Down"
echo " Record changes to the repository."
git commit -a -m "$commit"
echo " Down"
curl -u $uname https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
echo " Adds a remote named <name> for the repository at <url>."
git remote add origin "git@github.com:$uname/$repo_name.git"
echo " Down"
echo " Push all file to the repository, and set upstream."
git push -u origin master
echo " Down"
Echo " And finally let see the status of the repository."
git status
echo " The $repo_name repository has been completed."
echo " Bye Bye. And have a nice day."
