#!/bin/bash
set -e # If made error stop the script

uname=$(git config user.name)
repo_name=$(basename "$PWD")
echo "################################################################################"
echo ""
echo " Your GIT username is $uname."
echo ""
echo "################################################################################"
echo " The name of the current directory will be the name of the repository."
echo " The repository name is setting up for $repo_name."


read -p " Please write in the first commit: " commit

echo " Creating a README.md file."
echo "# $repo_name" > README.md

echo "################################################################################"
echo " Create an empty Git repository."
git init

echo "################################################################################"
echo " Add all files."
git add .

echo "################################################################################"
echo " Record changes to the repository."
git commit -m "$commit"

git branch -m main

echo "################################################################################"
echo " Adds a remote named <name> for the repository at <url>."
curl -s -H "Authorization: token $ATOKEN" -d "{\"name\":\"$repo_name\"}" https://api.github.com/user/repos

git remote add origin "git@github.com:$uname/$repo_name.git"

echo "################################################################################"
echo " Push all file to the repository, and set upstream."
git push -u origin main

echo "################################################################################"
echo " And finally let see the status of the repository."
git status

echo "################################################################################"
echo " The $repo_name repository has been completed."
echo " Bye Bye. And have a nice day."
echo "################################################################################"
