#!/bin/bash
read -p " Add meg a repo nevét: " reponame
read -p " Írd be az első commit-ot:" commit
git init
git add .
git commit -m "$commit"
curl -u 'zsoltibaba37' https://api.github.com/user/repos -d '{"name":"$reponame"}'
git remote add origin git@github.com:zsoltibaba37/$reponame.git
git push origin master
